config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :dishes do
    resources :reviews
  end
  root 'dishes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :reviews
  acts_as_votable

  validates_presence_of :name
  validates_presence_of :image
  validates_presence_of :cost
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dish
  validates_presence_of :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_message

  validates_presence_of :email

  def send_welcome_message
    CustomerMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
  @dishes = Dish.all.order(rating: :desc)
end

def show
  @dish = Dish.find(params[:id])
  if params[:upvote]
    @dish.liked_by current_user
    @dish.rating =+ 1
    @dish.save
    render :show
  end
end

def new
  @dish = Dish.new
end

def create
  @dish = Dish.new(dish_params)
  @dish.rating = 0
  if @dish.save
    flash[:notice] = "Dish succesfully added!"
    redirect_to dishes_path
  else
    flash[:notice] = "Dish not added!"
    render :new
  end
end

def edit
  @dish = Dish.find(params[:id])
end

def update
  @dish = Dish.find(params[:id])
  if @dish.update(dish_params)
    flash[:notice] = "Dish Updated!"
    redirect_to dishes_path
  else
    flash[:alert] = "Dish Update Failed!"
    redirect_to dishes_path
  end
end

def destroy
  @dish = Dish.find(params[:id])
  @dish.destroy
  flash[:notice] = "Dish Deleted!"
  redirect_to dishes_path
end

private
def dish_params
  params.require(:dish).permit(:name, :cost, :image)
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @dish = Dish.find(params[:dish_id])
    @review = @dish.reviews.new
  end

  def create
    @dish = Dish.find(params[:dish_id])
    @review = @dish.reviews.new(review_params)
    if @review.dish.save
      flash[:notice] = "Review Saved!"
      redirect_to dish_path(@review.dish)
    else
      flash[:notice] = "Review not Saved!"
      render :new
    end
  end

  def destroy
    @dish = Dish.find(params[:dish_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review Deleted!"
    redirect_to dish_path(@review.dish)
  end

private
  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/dishes/_form.html.erb


<div class="dish-form">
<%= form_for @dish, url: dishes_path, html: { multipart: true } do |f| %>
  <%= f.text_field :name, :class => 'form-control', :placeholder => "name" %>
  <%= f.text_field :cost, :class => 'form-control', :placeholder => "cost"%>
  <%= f.text_field :image, :class => 'form-control', :placeholder => "image url"%>
  <%= f.submit 'Save', :class => "btn btn-primary"%>
<% end %>


</div>

app/views/dishes/edit.html.erb
<h1>Edit this Dish</h1>


<%= render 'form' %>

app/views/dishes/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Welcome to Son of Cod!</h2></div>
  <div class="panel-body"><h3>A local seafood restaurant where the reviews decide what gets on the menu! Leave reviews and likes,<br> the <strong>top 4 dishes get on the menu!</strong></h3></div>
</div>
<br>
<h2>Current Menu:</h2>
<div class="row">
  <% if @dishes.any? %>
    <% @dishes.first(4).each do |d| %>
      <div class="col-md-3 well">
        <%= link_to image_tag(d.image), dish_path(d) %>
        <br>
        Dish: <%= link_to d.name, dish_path(d) %>
        <br>
        Price: $<%= d.cost %>
        <br>
        Votes: <%= d.rating %>
      </div>
    <% end %>
  <% else %>
    <p>
      There are no dishes yet!
    </p>
  <% end %>
</div>
<div class="admin_add">
  <% if current_user.admin? %>
       Click <%= link_to "here", new_dish_path %> to add a dish.
  <% end %>
  <hr>
  <br>
  <h2>Full list of Dishes, vote for your favorite and it might make it on the menu:</h2>
  <br>
  <% @dishes.each do |d| %>
    <div class="col-md-3 well">
      <%= link_to image_tag(d.image), dish_path(d) %>
      <br>
      Dish: <%= link_to d.name, dish_path(d) %>
      <br>
      Price: $<%= d.cost %>
      <br>
      Votes: <%= d.rating %>
    </div>
  <% end %>
</div>

app/views/dishes/new.html.erb
<h1>Create new Dish</h1>

<%= render 'form' %>

app/views/dishes/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h1>Details for <%= @dish.name %></h1></div>
  <div class="panel-body">
    <%= image_tag @dish.image, :class => "dish-images" %> <br>
    <h3>Price:</h3> <h4>$<%= @dish.cost %></h4> <br>
    <span class="vote-number">Current Score: <%= @dish.get_likes.size %></span> |
    <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span> <%= link_to "Vote", :upvote => @dish.id %>
    <br>
    <h3>Reviews for <%= @dish.name %>: </h3>
    <% if @dish.reviews.any? %>
      <% @dish.reviews.each do |d| %>
        <div class="col-md-3 review-section">
          <%= d.content %> <small>- Posted: <%= time_ago_in_words(d.created_at) %> ago</small>
          <br>
          <% if current_user.admin? %>
            <%= link_to "Delete Review", dish_review_path(@dish, d),:data => {:confirm => "Are you sure?",:method => "delete"} %>
          <% end %>
        </div>
        <% end %>
      <% end %>
      <br>
      <p id="add-review">
        Click <%= link_to "here", new_dish_review_path(@dish) %> to add a review.
      </p>
    <br>

  </div>

</div>
<% if current_user.admin? %>
  <%= link_to "Edit Dish", edit_dish_path(@dish) %> |
  <%= link_to "Delete Dish", dish_path(@dish),:data => {:confirm => "Are you sure?",:method => "delete"} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seafood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
           <div class="container">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                   <%= link_to "Son of Cod", root_path, class:"navbar-brand" %>
               </div>
               <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                   <ul class="nav navbar-nav">
                     <% if user_signed_in? %>
                       <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                     <% else %>
                         <li><%= link_to "Sign Up", new_user_registration_path %></li>
                         <li><%= link_to "Log In", new_user_session_path %></li>
                     <% end %>
                     <li class="notice text-muted pull-right"><%= notice %></li>
                     <li class="alert text-muted pull-right"><%= alert %></li>
                   </ul>
               </div>
               <!-- /.navbar-collapse -->
           </div>
           <!-- /.container -->
       </nav>
       <div class="container body-container">

         <%= yield %>
       </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<div class="dish-form">
<%= form_for [@dish, @review] do |f| %>
  <%= f.text_field :content, :class => 'form-control', :placeholder => "review" %>
  <%= f.submit 'Save', :class => "btn btn-primary"%>
<% end %>

</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>